#include <stdio.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <string.h>
#include <bits/stdc++.h>
#include "Socket/Socket.h"
#include "json/json.hpp"
#include <netinet/tcp.h>
#include "redis/hiredis/hiredis.h"
//#include "redis/redis-plus-plus/src/sw/redis++/redis++.h"

#include "domObjects/bed.h"
#include "domObjects/chair.h"
#include "domObjects/lamp.h"
#include "domObjects/wall.h"
#include "domObjects/pillar.h"
#include "domObjects/fridge.h"
#include "domObjects/door.h"
